# Generated by Django 3.2.12 on 2024-02-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Myuser',
        ),
    ]
