# Generated by Django 5.0.2 on 2024-03-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_commentreport_details_alter_commentreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
    ]
