# Generated by Django 4.0.2 on 2024-03-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tag_project_creator_featuredproject_similarproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='myapp.Tag'),
        ),
    ]
