# Generated by Django 5.0.2 on 2024-03-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myuser_profile_pic'),
        ('myapp', '0003_project_images_alter_picture_project'),
    ]

    operations = [
    ]
