# Generated by Django 5.0.2 on 2024-03-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20240308_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
